name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  package:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: xvfb-run -a npm test

      - name: Set temporary version
        if: github.ref_type != 'tag'
        run: |
          # Get current version using node
          VERSION=$(node -p "require('./package.json').version")
          
          # Generate timestamp
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          
          # New version
          NEW_VERSION="${VERSION}-dev.${TIMESTAMP}"
          
          echo "Setting temporary version to $NEW_VERSION"
          
          # Update package.json using npm version to ensure file is updated correctly without git tag
          npm version $NEW_VERSION --no-git-tag-version

      - name: Package Extension
        id: package_step
        run: |
          # Get package name and version
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")
          
          # Define VSIX filename
          VSIX_NAME="${PACKAGE_NAME}-${VERSION}.vsix"
          echo "VSIX_NAME=$VSIX_NAME" >> $GITHUB_ENV
          
          # Package
          npx @vscode/vsce package --out $VSIX_NAME

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VSIX_NAME }}
          path: ${{ env.VSIX_NAME }}

      - name: Save PR Metadata
        if: github.event_name == 'pull_request'
        run: |
          mkdir -p pr_meta
          echo "${{ github.event.number }}" > pr_meta/pr_number.txt
          echo "${{ steps.upload_artifact.outputs.artifact-url }}" > pr_meta/artifact_url.txt
          echo "${{ env.VSIX_NAME }}" > pr_meta/vsix_name.txt

      - name: Upload PR Metadata
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: pr_meta
          path: pr_meta/

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.VSIX_NAME }}
